var GAME_LEVELS = [
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                 xx                                             ",
   "                              o o  y                                            ",
   "                                    x                                           ",
   "         | |                  xx     y!!                                        ",
   "                                       x               ooo                      ",
   "                                        y                                       ",
   "                     o o     x!!x        x      xx    xxxxxx                    ",
   "  o o                        x!!x         y!!                                   ",
   "                    xxx       xx           x                                    ",
   " yyyyy                  o                   y                                   ",
   "               c                             x                           oo     ",
   "             xxxx       xx                                                      ",
   "      @                                                                     e   ",
   "  xxxxxxxx                                                 x           yx!!xx   ",
   "              x!!!!!!!!!!!!!!!!!!!!!!!!!!x                  y         x         ",
   "               x!!!!!!!!!!!!!!!!!!!!!!!!x                x   x       y          ",
   "                x!!!!!!!!!!!!!!!!!!!!!!x               x      y     x           ",
   "                 x!!!!!!!!!!!!!!!!!!!!x              x         x o y            ",
   "                  x!!!!!!!!!!!!!!!!!!x           oo             y x             ",
   "                    xxxxxxxxxxxxxxxxx          !!xx!!            !              "],
  ["      @                                                                                                       ",
   "   xxxxxxxx                                                       oo                                          ",
   "           xxxxxxxx            oo                                                                             ",
   "                   xxxxxxxx                                               xxxxxxxx                            ",
   "                           !!!!!xx!!!x                        xx!!!xx!!!!!                                    ",
   "                                     x                        x                                               ",
   "                                     x           ooo          x                                               ",
   "                                     y                        y                                               ",
   "      oo                             y    oo             oo   y                                               ",
   "           oo                        y                        y                                               ",
   "     xxxx                             xxx!!!xx        xx!!!xxx                                        xxxx    ",
   "          !yyy!        oo                    x!!!  !!!x                                              x        ",
   "                 !!!                    ooo  x!!!  !!!x                                      oo     x         ",
   "                                             y!!!  !!!y                                            x          ",
   "                    xxxxxx            xxxxxxxy                                            oo      x           ",
   "                            xxx                                                                  x            ",
   "                                !!!                                                             x             ",
   "                                xxx    yyyyyy    yyy                                   oo      x              ",
   "                                             xxxx                                             x               ",
   "                                                                                             x                ",
   "          ooo                                                                              !!                 ",
   "                 =       oooo                               !!!!!!!                       x                   ",
   "                         oooo                               !!!!!!!                      x                    ",
   "        xx   xx                                             !!!!!!!                     x                     ",
   "          !!!                                                                          x                      ",
   "                                                     xxxx            xxxx  yyyyyyyyyyyy                       ",
   "          ooo              xx!!!!!xx                                                                          ",
   "                   xxxxxxxx             yyyyyyyy             yyyy                                             ",
   "  xxxxxxxxxxxxxxxxx                                                                                           ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],
  ["                                                                                                              ",
   "   xx  xx                                                                                                     ",
   "    ooo x                  x     xxxx                              xxxx   xxxx                                ",
   "   @ ooox                 x !!!!!    x          oooooooo          x   ! o !                                   ",
   "   xx  xx           xxxxxx            x                          x    ! o !                                   ",
   "   x                x                  x         xxyxyx         x     ! o !                                   ",
   "   x oooo           x                   x                      x      ! o !                                   ",
   "   xxxxxxx!!!!!xxxxxx                    x!!!!!!!!!!!!!!!!!!!!x       ! o !                                   ",
   "                                          x!!!!!!!!!!!!!!!!!!x        ! o !                                   ",
   "                                           x!!!!!!!!!!!!!!!!x         ! o !                                   ",
   "                                                                      ! o !                                   ",
   "                                                                   xxx  o  xxx                                ",
   "                                                                                                              ",
   "                oooooooo                          oooooooo                                                    ",
   "               o        o                        o        o                                                   ",
   "                                                                   xxxx    x       x                          ",
   "                                                                  x   x   x    oo    x                        ",
   "                 xxxxxx                 xxxxxx              xxxxxx         !!     xxxxx  o     o  xxxxx       ",
   "           xxxxxx      xxxxxx                                                                                 ",
   "                                                                                                              ",
   "                                                       =                                                      ",
   "                                                                                                              ",
   "                                               !!!!!   o   !!!!!                                              ",
   "                                                    !  o  !                                                   ",
   "                  o o o o o o                       !  o  !                       o o o o o o                 ",
   "                 o o o o o o                           o                          o o o o o o                 ",
   "                o o o o o o                          ooooo                         o o o o o o                ",
   "               o o o o o o                                                          o o o o o o               ",
   "              o o o o o o                              =                             o o o o o o              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                   xxxyyyxxx                                                  ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "  x                           x    xxx    xx!!!xx                        xxxxx                             x  ",
   "  x                           x           x     x                        x o x                             x  ",
   "  x                           xx          x     x                        x x x                             x  ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              "],
  ["                                                                                                              ",
   "                                    xxx                      xxx                                              ",
   "                                       xx       ooooo       xx                                                ",
   "                                        x!  @  o     o     !x                                                 ",
   "                                         xxxxx         xxxxx                                                  ",
   "                                   o      xx             xx                                                   ",
   "                                                  o                  ooo                                      ",
   "                                 xxxxx                             o     o                                    ",
   "                                            o                     o       o                                   ",
   "                                      xxxxxxxxxxxx                o       o                                   ",
   "    xxxxxxx                                                   yyy  o     o  yyy                               ",
   "           xxxxx                                                     ooo                                      ",
   "                xxxxxxxx  o                                        yyyyyyy                                    ",
   "                                                           o                                                  ",
   "          o              xxx                              xyx                                                 ",
   "                                                                                 |  |                         ",
   "                                o                     o                                                       ",
   "                                                     xyx                          o                           ",
   "                               xxx                                              xyyyyx                        ",
   "                                                                                                              ",
   "              o            o                           o                                                      ",
   "                                                     yyyyxx     xx                                            ",
   "             xxx   !!!   xxx         xxx                                                    x                 ",
   "                                                                                                              ",
   "                                                                                                              ",
   "  xxxxxxxxxxx                                                                                                 ",
   "                                                                                          x                   ",
   "  x         x   x       x   x       x   x                                     x     x                         ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
